'use client';

import { useState } from 'react';
import { signIn } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [isLoading, setIsLoading] = useState(false);
  const handleSubmit = async (event: React.FormEvent) => { event.preventDefault(); setIsLoading(true); setError(''); try { const result = await signIn('credentials', { email, password, redirect: false }); if (result?.error) setError('Invalid email or password'); else { router.push('/dashboard'); router.refresh(); } } catch { setError('An error occurred. Please try again.'); } finally { setIsLoading(false); } };
  return <main className="flex min-h-screen items-center justify-center px-5 py-12"><div className="w-full max-w-md"><Link href="/" className="mb-10 flex items-center justify-center gap-2.5 font-semibold tracking-tight text-foreground"><span className="grid size-8 place-items-center rounded-lg bg-accent text-accent-foreground">C</span>CareerSync</Link><section className="rounded-xl border border-border bg-surface p-6 shadow-sm sm:p-8"><p className="text-sm font-medium text-muted">WELCOME BACK</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-foreground">Sign in to CareerSync</h1><p className="mt-2 text-sm leading-6 text-muted">Continue your focused job search.</p>{error && <div className="mt-5 rounded-lg border border-danger bg-danger-surface p-3 text-sm text-danger">{error}</div>}<form onSubmit={handleSubmit} className="mt-7 space-y-5"><label className="block text-sm font-medium text-foreground">Email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background px-3.5 py-2.5 text-foreground outline-none transition focus:border-foreground" placeholder="you@example.com" /></label><label className="block text-sm font-medium text-foreground">Password<input type="password" required value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background px-3.5 py-2.5 text-foreground outline-none transition focus:border-foreground" placeholder="••••••••" /></label><button type="submit" disabled={isLoading} className="w-full rounded-lg bg-accent px-4 py-3 text-sm font-medium text-accent-foreground transition-opacity hover:opacity-85 disabled:cursor-not-allowed disabled:opacity-50">{isLoading ? 'Signing in…' : 'Sign in'}</button></form><div className="my-6 flex items-center gap-3 text-xs text-subtle before:h-px before:flex-1 before:bg-border after:h-px after:flex-1 after:bg-border">OR</div><button onClick={() => signIn('google', { callbackUrl: '/dashboard' })} className="w-full rounded-lg border border-border px-4 py-3 text-sm font-medium text-foreground transition-colors hover:bg-surface-muted">Continue with Google</button><p className="mt-6 text-center text-sm text-muted">New to CareerSync? <Link href="/register" className="font-medium text-foreground underline underline-offset-4">Create an account</Link></p></section></div></main>;
}
