'use client';

import { useRef, useState } from 'react';

export function FileUpload() {
  const [isDragging, setIsDragging] = useState(false); const [file, setFile] = useState<File | null>(null); const [isUploading, setIsUploading] = useState(false); const [result, setResult] = useState<{ success: boolean; message: string; textPreview?: string } | null>(null); const fileInputRef = useRef<HTMLInputElement>(null);
  const selectFile = (selected: File | undefined) => { if (!selected) return; if (selected.type === 'application/pdf') { setFile(selected); setResult(null); } else setResult({ success: false, message: 'Please choose a PDF document.' }); };
  const handleUpload = async () => { if (!file) return; setIsUploading(true); setResult(null); const formData = new FormData(); formData.append('resume', file); try { const response = await fetch('/api/upload', { method: 'POST', body: formData }); const data = await response.json(); setResult(response.ok ? { success: true, message: data.message, textPreview: data.textPreview } : { success: false, message: data.error || 'Upload failed' }); } catch { setResult({ success: false, message: 'An unexpected error occurred' }); } finally { setIsUploading(false); } };
  return <div className="mx-auto mt-7 max-w-2xl"><div role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') fileInputRef.current?.click(); }} onDragOver={(event) => { event.preventDefault(); setIsDragging(true); }} onDragLeave={() => setIsDragging(false)} onDrop={(event) => { event.preventDefault(); setIsDragging(false); selectFile(event.dataTransfer.files[0]); }} onClick={() => fileInputRef.current?.click()} className={`cursor-pointer rounded-xl border border-dashed p-10 text-center transition-colors ${isDragging ? 'border-foreground bg-surface-muted' : 'border-border-strong hover:border-foreground hover:bg-surface-muted/50'}`}><input type="file" ref={fileInputRef} className="hidden" accept="application/pdf" onChange={(event) => selectFile(event.target.files?.[0])} /><svg className="mx-auto size-7 text-muted" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="M12 16V4m0 0L8 8m4-4l4 4M4 15v4a1 1 0 001 1h14a1 1 0 001-1v-4" /></svg><p className="mt-4 text-sm font-medium text-foreground">{file ? file.name : 'Choose a resume or drop it here'}</p><p className="mt-1 text-sm text-muted">PDF up to your browser&apos;s upload limit</p></div>{file && <div className="mt-4 flex items-center justify-between rounded-lg border border-border bg-surface-muted px-4 py-3"><span className="truncate pr-4 text-sm text-muted">Ready to upload</span><button onClick={handleUpload} disabled={isUploading} className="shrink-0 rounded-lg bg-accent px-4 py-2 text-sm font-medium text-accent-foreground transition-opacity hover:opacity-85 disabled:cursor-not-allowed disabled:opacity-50">{isUploading ? 'Uploading…' : 'Upload resume'}</button></div>}{result && <div className={`mt-5 rounded-lg border p-4 ${result.success ? 'border-success bg-success-surface text-success' : 'border-danger bg-danger-surface text-danger'}`}><p className="text-sm font-medium">{result.message}</p>{result.textPreview && <pre className="mt-4 max-h-60 overflow-auto rounded-md border border-border bg-surface p-3 text-left text-xs leading-5 text-muted whitespace-pre-wrap">{result.textPreview}</pre>}</div>}</div>;
}
